### ISSUE TITLE
[Regression]已结束比赛中时间显示问题

### ISSUE THREAD

**Issue by lovealba** [VOID001/NEUOJ-bug-report#104]
![image](https://cloud.githubusercontent.com/assets/19867160/15982720/94f03638-2fc2-11e6-8904-85f9da7875b0.png)

如图 0无限变长

**Comment by VOID001** [comment]
@DYS1230

**Comment by VOID001** [comment]
Thanks for reporting, this is a regression, we will fix it ASAP

**Comment by VOID001** [comment]
@DYS1230

**Comment by DYS1230** [comment]
六天前已经提交了merge request

**Comment by VOID001** [comment]
Merged

**Comment by VOID001** [comment]
Fixed
