### ISSUE TITLE
Profile页面的问题

### ISSUE THREAD

**Issue by satouriko** [VOID001/NEUOJ-bug-report#123]
上传超过 1M 的头像就会 Whoops, looks like something went wrong.
选择头像这里前端排版有问题
![image](https://cloud.githubusercontent.com/assets/18373361/19605669/dbdf16ec-97ee-11e6-9e8b-630eafc76db3.png)

**Comment by VOID001** [comment]
前端问题， 我们会尽快修复

**Comment by VOID001** [comment]
FIxed
