### ISSUE TITLE
oj的contest存在漏题风险

### ISSUE THREAD

**Issue by whoisnian** [VOID001/NEUOJ-bug-report#147]
4月7日周五中午在oj上偶然看到的   
[手机截图](https://whitewings.cn/share/upload/2017-4-7-phone-screenshot.PNG)   
4月9日周日下午比赛题目   
[比赛题目](https://whitewings.cn/share/upload/2017-4-9-contest.png)

**Comment by whoisnian** [comment]
在GitHub网页上传图片总是失败，只能把链接放这里了

**Comment by LeeeeoLiu** [comment]
收到

**Comment by VOID001** [comment]
@whoisnian You https cert is not valid

**Comment by whoisnian** [comment]
@VOID001 
Because I reset the server when I deleted my blog on wordpress. 
Now I have updated the links.
