### ISSUE TITLE
[Urgent!!!] Problem Display Raw HTML (Not Rendered) 

### ISSUE THREAD

**Issue by VOID001** [VOID001/NEUOJ-bug-report#15]
Problems load from hustoj
Displays RAW HTML

**Comment by zarcoder** [comment]
问题的 Sample input 和 Sample Output显示好像不是那么完美
题目的分页应该和老OJ一样有那种第一页，第二页的链接

**Comment by VOID001** [comment]
"题目的分页应该和老OJ一样有那种第一页，第二页的链接"
@DYS1230 is fixing this bug, patch rejected, will be fixed in next patch

**Comment by VOID001** [comment]
> 题目的分页应该和老OJ一样有那种第一页，第二页的链接
@zarcoder  fixed

**Comment by VOID001** [comment]
Fixed
