### ISSUE TITLE
Contest中ranklist排名不正确

### ISSUE THREAD

**Issue by whoisnian** [VOID001/NEUOJ-bug-report#153]
[CPP-2017-类（1）的Ranklist](https://oj.neu.edu.cn/contest/61/ranklist)  
![tim 20170609084540](https://user-images.githubusercontent.com/23057947/26956618-a55da954-4cf1-11e7-9ec3-900fbdabc53e.png)  
12 : 58 : 22在111 : 06 : 07后，下面还有类似的，感觉是把两个时间以字符串的形式比较的。

**Comment by VOID001** [comment]
@onionwyl
