### ISSUE TITLE
[contest-system] invalid contest id leads to a crash screen

### ISSUE THREAD

**Issue by DuckSoft** [VOID001/NEUOJ-bug-report#159]
for example, go https://oj.neu.edu.cn/contest/233333 and you will see a crash screen:
![crash_screen](https://user-images.githubusercontent.com/7822648/29215816-10550fc6-7edf-11e7-90bf-f3d232e4aa9e.png)

i don't think it right to show this stuff to users lol

**Comment by VOID001** [comment]
Fixed
