### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by zarcoder** [VOID001/NEUOJ-bug-report#17]
Problem List页，显示题目的那一行都可以点击进入题目了
之前是好像是Problem ID可点击
现在修改之后给人感觉没有锚点了，我觉得还是就Problem ID和 Title 两项可以点击就可以
你们觉得呢
我看了一下老OJ，还有HDU的，还有HIT的，好像都是只有Title可点击
@VOID001 @Hsword @su526664687

**Comment by VOID001** [comment]
那就做个高亮效果吧,鼠标移动到可以点击的题目上的时候将这一条高亮一下, 并且现在的鼠标指针已经变成 手形了, 应该能看出来, 而且整个一条都能点不影响href, 如果有href的话 会先处理href的

**Comment by chenhongbiao** [comment]
Problem List 中被高亮题目的Title有些看不清，建议换种高亮颜色:fallen_leaf:

**Comment by VOID001** [comment]
Fixed
