### ISSUE TITLE
Status页面的Problem Title应该链接跳转到题目

### ISSUE THREAD

**Issue by zarcoder** [VOID001/NEUOJ-bug-report#23]
+ Status页面的Problem Title应该链接跳转到题目，现在好像没有链接
+ Status页面，鼠标悬浮在某一行的话，背景颜色和这个提交是用户自身提交的题目颜色一样，这个应该有区别吧
+ CE时，显示的信息不全

  -  本机编译出错提示

  -  ![1](https://cloud.githubusercontent.com/assets/2095041/13732695/445fa9f0-e9c3-11e5-997c-9f9235363293.png)

  -  OJ对编译出错的提示

  -  ![2](https://cloud.githubusercontent.com/assets/2095041/13732696/4462315c-e9c3-11e5-8979-2aa8d62fd6c6.png)

**Comment by VOID001** [comment]
CE Fixed

**Comment by VOID001** [comment]
Status页面，鼠标悬浮在某一行的话，背景颜色和这个提交是用户自身提交的题目颜色一样，这个应该有区别吧

This is not a bug, all the area that can access by current user will turn highlight

**Comment by VOID001** [comment]
Fixed
