### ISSUE TITLE
请求加入USACO Training题库

### ISSUE THREAD

**Issue by catsworld** [VOID001/NEUOJ-bug-report#28]
作为一些基础以及细节的学习USACO真的适合很棒的题库，希望大家都可以去做。

**Comment by VOID001** [comment]
@zarcoder

**Comment by zarcoder** [comment]
可以啊

**Comment by VOID001** [comment]
@catsworld If you can provide a well-formatted data and problem that's suitable for ACM-ICPC mode contest, We can add a Tutorial System using the Problem Database your provided

**Comment by zarcoder** [comment]
@catsworld 你有USACO的所有题目的数据么？

**Comment by catsworld** [comment]
@zarcoder 应该有，或者至少能找到

**Comment by VOID001** [comment]
Now traning system is working In Progress

**Comment by VOID001** [comment]
No problem imported yet
