### ISSUE TITLE
Bug: display errors about "Problem Description~ Input~ "

### ISSUE THREAD

**Issue by zarcoder** [VOID001/NEUOJ-bug-report#31]
在Problem编辑页，填写的数据
注意input里面是没有填任何东西的
Output里面只有一个Hello World!
![qq 20160317102803](https://cloud.githubusercontent.com/assets/2095041/13834581/30d21b24-ec2b-11e5-8e90-51aaff3f5265.png)

但是在查看题目的时候
Input和Output都显示的Problem Description的东西
![qq 20160317102740](https://cloud.githubusercontent.com/assets/2095041/13834579/27949762-ec2b-11e5-9e6e-999005c19eb0.png)

**Comment by VOID001** [comment]
Fixed
