### ISSUE TITLE
Bug: 管理员界面查看题目的时候出错

### ISSUE THREAD

**Issue by zarcoder** [VOID001/NEUOJ-bug-report#38]
@VOID001 
http://202.118.31.226/dashboard/problem/p/1

**Comment by VOID001** [comment]
This is a regression caused by 43044e2a

**Comment by VOID001** [comment]
Not only admin crash , user visit /problem/p/1 also crash

**Comment by VOID001** [comment]
@onionwyl \

**Comment by VOID001** [comment]
Fixed
