### ISSUE TITLE
[Urgent!!!]比赛的前端计时器的时间和后端的时间不同步

### ISSUE THREAD

**Issue by NEU20133823** [VOID001/NEUOJ-bug-report#4]
如果在比赛开始之前登陆进去比赛，那么比赛开始后还是看不了题，必须退出账号再进去才能看

**Comment by VOID001** [comment]
@su526664687 问题应该是 前端显示时间和服务器实际时间不符

**Comment by su526664687** [comment]
这个问题，用户手动刷新一下页面能看到题目吗 @NEU20133823

**Comment by NEU20133823** [comment]
@su526664687 我记得是不行的

**Comment by VOID001** [comment]
这个bug应该更改为: 前端的JS倒计时器和后端的服务器时间不同步

**Comment by su526664687** [comment]
额，这个之后修正一下

**Comment by VOID001** [comment]
Not fixed now

**Comment by VOID001** [comment]
Maybe fixed now, need test in contest

**Comment by VOID001** [comment]
Fixed
