### ISSUE TITLE
The color is not really good

### ISSUE THREAD

**Issue by xfangfang** [VOID001/NEUOJ-bug-report#46]
sorry for my english.

**Comment by VOID001** [comment]
Please give some detailed info, you can use Chinese, too

**Comment by xfangfang** [comment]
厉害，秒回啊，个人感觉新oj配色不是很好看，略发紫了，很喜欢之前的蓝色，不过调整了应该是有原因的，只是发表一下个人见解^_^

**Comment by VOID001** [comment]
谢谢你的反馈~~~ 我们会认真对待每一条反馈的~  (｡･ω･)ﾉﾞ 
@su526664687 @DYS1230

**Comment by VOID001** [comment]
Others also mentioned the color of OJ, maybe it is necessary to change
