### ISSUE TITLE
新OJ没有对用户已过题目的显示功能

### ISSUE THREAD

**Issue by 1158191255** [VOID001/NEUOJ-bug-report#47]
求问新OJ的problem没有显示那道题过了的地方么？过了的题还可以提交啊...0.0

**Comment by VOID001** [comment]
我们会在下面的版本加上这个功能哒～过了的题还可以提交  不过不会重复计算分数辣以后 ~o(〃'▽'〃)o
多谢反馈

**Comment by VOID001** [comment]
FIxed and merged
