### ISSUE TITLE
比赛通过文件导入用户有问题

### ISSUE THREAD

**Issue by lamxTyler** [VOID001/NEUOJ-bug-report#48]
通过文件导入并不能导入用户，而且导入用的文件好像丢失了。

**Comment by VOID001** [comment]
This is stub now, not implemented

**Comment by VOID001** [comment]
Implemented, testing

**Comment by VOID001** [comment]
Fixed, @su526664687 please add error message when importing User List

**Comment by Jinming-Su** [comment]
fixed
