### ISSUE TITLE
[Urgent!!!]比赛的fb显示有问题

### ISSUE THREAD

**Issue by NEU20133823** [VOID001/NEUOJ-bug-report#49]
如果没有什么特殊设置的话，第三次月赛ABD三题的fb都不对

**Comment by VOID001** [comment]
可否说明一下FB应该是谁, 现在是谁?
并提供相关的截图证明 Thanks

**Comment by NEU20133823** [comment]
A应该是程国宇，现在是我；B应该是20143717，现在是余谦；D应该是立波，现在也是我0.0
截图：
![screenshot_2016-03-27-17-01-47_com android browse](https://cloud.githubusercontent.com/assets/16102286/14065052/81179c0c-f44c-11e5-9054-7afd985af158.png)

**Comment by VOID001** [comment]
OK, Now the cause of the bug is unknown

**Comment by VOID001** [comment]
@onionwyl @Hsword  This bug is critical, Please figure out the problem ASAP

**Comment by VOID001** [comment]
When rejudge the whole problem, the fb display is correct

**Comment by VOID001** [comment]
Onion provide a solution, Reviewing Now

**Comment by VOID001** [comment]
Ranklist Status Fixed, But User Contest Problem List Page not fixed, New bug opened #50
