### ISSUE TITLE
[Testing] Ranklist题量统计bug

### ISSUE THREAD

**Issue by catsworld** [VOID001/NEUOJ-bug-report#51]
AC后WA再AC，数量+1。

**Comment by VOID001** [comment]
Thanks for your reporting, We will fix it ASAP

**Comment by VOID001** [comment]
AC AC will not change the Total number

**Comment by VOID001** [comment]
Each AC WA AC will add one more count of total AC problems

**Comment by VOID001** [comment]
@onionwyl Fixing it, testing the whether it cause a regression

**Comment by VOID001** [comment]
Maybe Fixed, Need for future test

**Comment by VOID001** [comment]
Fixed
