### ISSUE TITLE
无故被登出

### ISSUE THREAD

**Issue by ligy118** [VOID001/NEUOJ-bug-report#55]
登陆后进昨天的课程(comtest>>2016-Lesson01)，先看了榜单，然后又点了状态看提交情况，就需要重新登陆
win 7
chrome(机房网自带翻墙效果好棒≧▽≦)

**Comment by VOID001** [comment]
This is because we use session not cookie to store the user login state. 
And What's more the PC in NEU has auto-recovery mode enabled , Which means when you shutdown the PC, all the data you modifed may lost, so the cookie is lost, too

**Comment by VOID001** [comment]
Maybe not a bug , Closed
