### ISSUE TITLE
Frontend: 显示的行间距，容易跟隔行混淆

### ISSUE THREAD

**Issue by woodiness** [VOID001/NEUOJ-bug-report#59]
![970vtby 1bj zotkbmweghv](https://cloud.githubusercontent.com/assets/15183144/14224895/09e7c5ec-f8e0-11e5-8e26-b83ebeeffa63.png)

**Comment by VOID001** [comment]
@su526664687 @DYS1230

**Comment by catsworld** [comment]
@VOID001 疑似给值问题，并没有设置错误的行间距，相反源码中可以查到多余空行，只有Sample Input、Sample Output、Source三栏出现此问题。

**Comment by VOID001** [comment]
You mean this is not a frontend bug? We will look carefully
