### ISSUE TITLE
关于前端的小建议

### ISSUE THREAD

**Issue by catsworld** [VOID001/NEUOJ-bug-report#6]
1. 右上角用户名处日后增加功能时请务必做成Dropdown。
2. 左上角图标+NEUOJ应该链接到首页而不是当前页。[Fixed]
3. 之前提过的导航栏鼠标经过样式字体颜色为黑不是很舒服的问题。
4. Promblem List和Content List中建议把一整条都做成链接而不是只能点击那几个文字。[Fixed]
5. Status页可以把本人的状态标色，然后本人状态可以点击View Source，右边一排不能点的View Source很闹心。[Fixed]
6. Dashboard回OJ的链接可以做在Logo里，感觉放在下面有点奇怪。

**Comment by VOID001** [comment]
@su526664687 Please fix 1, 5

**Comment by su526664687** [comment]
好的，逐渐修整中

**Comment by VOID001** [comment]
@su526664687  Fix 2 6 please~ , Previously the bug report is broken,

**Comment by VOID001** [comment]
2 4 5 fixed

**Comment by VOID001** [comment]
All fixed
