### ISSUE TITLE
Frontend: 因chrome插件某部件位置错误

### ISSUE THREAD

**Issue by ligy118** [VOID001/NEUOJ-bug-report#60]
插件：百度翻译
不打开“划词翻译”功能时没事，打开后
一旦选中字符（不包括空格和换行）
页面最下方的 Transcript show: 'Kamusta mundo!'
All Copyright©Reserved 2013-2016 NEU-ACM TEAM   Ver 1.0
会跑到中间并遮挡那个位置的题目（但不能遮挡图片，会被图片盖着hhh）

**Comment by VOID001** [comment]
Can you provide a screenshot?

**Comment by ligy118** [comment]
![2016-04-02 15 07 26](https://cloud.githubusercontent.com/assets/15182212/14224984/d9c246a8-f8e4-11e5-8639-4df03636e922.png)
![2016-04-02 15 06 54](https://cloud.githubusercontent.com/assets/15182212/14224983/d9927996-f8e4-11e5-8357-0d106e6daf17.png)

**Comment by VOID001** [comment]
@su526664687 @DYS1230

**Comment by VOID001** [comment]
This is a bug caused by third-party plugin, not so urgent to fix, delayed for fixing now

**Comment by su526664687** [comment]
This is a problem which I have not encountered, so now I only mark.

**Comment by VOID001** [comment]
Ignored
