### ISSUE TITLE
热身赛时出现了两次权限不足的CE

### ISSUE THREAD

**Issue by catsworld** [VOID001/NEUOJ-bug-report#64]
Compiling failed with exitcode 1, compiler output:
/bin/ld: reopening program: Permission denied

/bin/ld: final link failed: Permission denied
collect2: error: ld returned 1 exit status

如果没法解决可以判断两次提交代码相同如果后一次AC前一次就不计入罚时么，不然很伤。

**Comment by VOID001** [comment]
Please provide the runid

**Comment by catsworld** [comment]
2697 & 2760

**Comment by VOID001** [comment]
This is very unlikely to happen now, If happened we can use Rejudge to re-submit the problem

**Comment by catsworld** [comment]
需不需要开一个Rejudge申请的功能

**Comment by VOID001** [comment]
Currently no need , future will discard this judgehost, and this problem will not exist
