### ISSUE TITLE
[Urgent!!] Refresh too frequently will get 403 error

### ISSUE THREAD

**Issue by VOID001** [VOID001/NEUOJ-bug-report#65]
Server configuration error, I think, need to fix this

**Comment by catsworld** [comment]
不仅如此在403之前还会出现样式异常的现象

**Comment by VOID001** [comment]
Style error is also caused by 403, cannot load certain css js file

**Comment by VOID001** [comment]
Server configure Anti DDOS Module This caused by the wrong-config of this module

**Comment by VOID001** [comment]
Fixed
