### ISSUE TITLE
contest里明明有人交了两发虽然是WA 但是比赛AC率是0/0

### ISSUE THREAD

**Issue by koooyf** [VOID001/NEUOJ-bug-report#66]
RT

**Comment by VOID001** [comment]
Thanks for your reporting, we will figure what is wrong and fix this ASAP

**Comment by VOID001** [comment]
Bug Confirmed by local test

**Comment by onionwyl** [comment]
What cause this😂

**Comment by VOID001** [comment]
This is a bug caused by frontend, confirmed

**Comment by VOID001** [comment]
@catsworld Please report the issue individually

**Comment by VOID001** [comment]
Fixed
