### ISSUE TITLE
AC/Submission should display only the info before the user first ac this problem

### ISSUE THREAD

**Issue by VOID001** [VOID001/NEUOJ-bug-report#69]
@onionwyl  Please fix this, before the contest

**Comment by onionwyl** [comment]
ok

**Comment by catsworld** [comment]
这个应该仅针对contest的统计，题目统计应该还是允许多次提交的

**Comment by VOID001** [comment]
But if user brute submit AC code in the problem base, the problem AC/Submission will very near to 100%, also confused others

**Comment by VOID001** [comment]
Fixed
