### ISSUE TITLE
Frontend Pager should improve

### ISSUE THREAD

**Issue by VOID001** [VOID001/NEUOJ-bug-report#7]
Now only can navigate to next page , and prev page, need a interface for user to access any page , and , need to add last-page and first-page link @su526664687  @DYS1230

**Comment by su526664687** [comment]
是所有存在翻页的页面吗？@VOID001

**Comment by VOID001** [comment]
Yes

**Comment by VOID001** [comment]
Fixed some pager , not all fixed

**Comment by VOID001** [comment]
Submission pager not fixed, other pager fixed

**Comment by VOID001** [comment]
Status page pager is not necessary, marked as fixed
