### ISSUE TITLE
[Urgent!!!] 关于用户名的问题

### ISSUE THREAD

**Issue by zarcoder** [VOID001/NEUOJ-bug-report#71]
用户注册的时候，限制一下用户名不能全为数字，以防止有人注册成学号形式的

**Comment by VOID001** [comment]
Yes, I already notice this, @onionwyl Fix this please

**Comment by VOID001** [comment]
@onionwyl Please fix this ASAP

**Comment by VOID001** [comment]
@onionwyl Please fix this ASAP

**Comment by VOID001** [comment]
Done
