### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by KuroxD** [VOID001/NEUOJ-bug-report#76]
the function that finding by promblem ID in the status

**Comment by VOID001** [comment]
Please describe the problem in accurate and detailed description, this will help us find the bug and fix it

**Comment by VOID001** [comment]
Hello, thanks for your reporting
But we cannot figure out what you mean, or what bug you occur by your description, Please make a detailed description (__maybe include a picture or give the step-by-step operation__), If no detailed information given, the issue will be closed in 3 days
