### ISSUE TITLE
这两个横向排版效果好一些吧

### ISSUE THREAD

**Issue by zarcoder** [VOID001/NEUOJ-bug-report#77]
Url:  dashboard/problem/p/1#
![qq20160414-0](https://cloud.githubusercontent.com/assets/2095041/14514180/ff63786a-0220-11e6-8884-3a5016a308f7.png)

**Comment by zarcoder** [comment]
![qq 20160420154008](https://cloud.githubusercontent.com/assets/2095041/14666796/116d444a-070e-11e6-9c62-b7b4d3abbfbf.png)
这个布局有点问题
除了上面的说的那两个排列横向排列之外
table列，第一列应该是题目的id，然后宽度不需要那么大
@su526664687

**Comment by su526664687** [comment]
fixed
