### ISSUE TITLE
Why cannot visit other pages after register

### ISSUE THREAD

**Issue by Diaopeng** [VOID001/NEUOJ-bug-report#78]
为什么我注册比赛会停滞在profile那一页面，一直过不去啊，所以我无法注册比赛吗

**Comment by VOID001** [comment]
你好， 感谢你的反馈
目前OJ上没有注册类型的比赛，你说的应该是注册一个新用户到OJ， 用户注册之后， 需要完善一下个人信息，才允许继续操作， 请填写相应的信息，点击Save之后，就可以访问其他页面了， 我们在之后的版本中会加入一句话提醒用户填写必要信息的，如果问题得到解决请回复我们，我们会关闭这个issue， 如果没有解决则继续提供具体的错误信息
