### ISSUE TITLE
[Frontend] The Admin ranklist style wrong

### ISSUE THREAD

**Issue by VOID001** [VOID001/NEUOJ-bug-report#82]
![image](https://cloud.githubusercontent.com/assets/6134883/14694882/56cec530-0732-11e6-85fc-8924dee2629f.png)
See the picture above, when stu_no is too log, the display is ugly

**Comment by su526664687** [comment]
I will fixed.

**Comment by VOID001** [comment]
Please fix this together with #84

**Comment by su526664687** [comment]
fixed
