### ISSUE TITLE
Training系统编辑题目的时候 题目的Problem没法保存

### ISSUE THREAD

**Issue by zarcoder** [VOID001/NEUOJ-bug-report#83]
1.保存之后就丢失了
2.[chapter1] 章节最好有个名称或者说明之类的，在着就是chapter1的首字母大写一下比较好看

**Comment by VOID001** [comment]
Get, Minor fixes will be done right now
2. need an extra area for chapter, Which now we do not have

**Comment by VOID001** [comment]
1 Fixed
