### ISSUE TITLE
Frontend: Display error

### ISSUE THREAD

**Issue by VOID001** [VOID001/NEUOJ-bug-report#84]
1. ![image](https://cloud.githubusercontent.com/assets/6134883/14781147/60d3e8a4-0aa6-11e6-84ca-0fb3b25ebbeb.png)
2. In training index page, when point to a problem , cursor does not chage its style
3.Normal user can see some links that they shouldn't see in dashboard, such as language

**Comment by su526664687** [comment]
About problem 3, could you give me a example? @VOID001

**Comment by VOID001** [comment]
![image](https://cloud.githubusercontent.com/assets/6134883/14912959/30ba7df0-0dc5-11e6-9ac9-2881584bc014.png)
Normal user should not see executables , languages, users

**Comment by VOID001** [comment]
Fixed
