### ISSUE TITLE
NEUOJ还没有添加C++11特性呦

### ISSUE THREAD

**Issue by JuGyang** [VOID001/NEUOJ-bug-report#85]
加油哦！！！=。=

**Comment by xjkdev** [comment]
同时也没有c99...

**Comment by VOID001** [comment]
感谢反馈， 我们会尽快支持的

**Comment by satouriko** [comment]
**请尽快
因为看到很多新人学C++都是用C++ Primer第五版**

**Comment by satouriko** [comment]
希望这个被标记为urgent，第五版的书上来就介绍很多新特性，比如auto，范围for语句，oj过不了（因此让他们回去看第四版嘛觉得这样做好奇怪啊）
望速改善，翘足企首以待

**Comment by VOID001** [comment]
This will be a main feature when NEUOJ 2.0 released

**Comment by VOID001** [comment]
Done
