### ISSUE TITLE
Bug: 输入数据的格式在保存和展示上做什么修改了么？

### ISSUE THREAD

**Issue by zarcoder** [VOID001/NEUOJ-bug-report#95]
编辑的时候
![2016-05-25 2 13 08](https://cloud.githubusercontent.com/assets/2095041/15529859/028c1fe2-2283-11e6-9255-6c634c5d19c2.png)
查看的时候
![2016-05-25 2 13 16](https://cloud.githubusercontent.com/assets/2095041/15529866/11a2a05a-2283-11e6-8683-76585a128998.png)

**Comment by VOID001** [comment]
@DYS1230 Take a look at this issue

**Comment by DYS1230** [comment]
OK

**Comment by VOID001** [comment]
I think this is caused by a change on the style sheet

**Comment by zarcoder** [comment]
尽快修复这个bug
因为没法读题啦

**Comment by DYS1230** [comment]
修好了

**Comment by zarcoder** [comment]
修好了，服务器pull一下，晚上有课 @VOID001

**Comment by VOID001** [comment]
GET, I will check and merge now
