### ISSUE TITLE
Bug: 后台编辑某个已经存在的比赛的时候没法保存

### ISSUE THREAD

**Issue by zarcoder** [VOID001/NEUOJ-bug-report#97]
提示这个比赛已经存在
应该是编辑比赛的保存的时候，你们也当create比赛来处理的
![2016-05-25 4 20 29](https://cloud.githubusercontent.com/assets/2095041/15532929/c63ad3c8-2294-11e6-8cd7-ddb1f9e62899.png)

另外
比赛过期之后管理员也应该能编辑
这个我之前说过了

**Comment by VOID001** [comment]
This is a regression = = Don't know who cause the bug now

**Comment by DYS1230** [comment]
。。。。。都是我的锅

**Comment by VOID001** [comment]
Fixed
