### ISSUE TITLE
比赛Pending时间显示的小问题

### ISSUE THREAD

**Issue by zarcoder** [VOID001/NEUOJ-bug-report#98]
这个pending的时间，应该是距比赛开始的时间吧，这个显示的是距离结束的时间似乎
![2016-05-25 4 20 38](https://cloud.githubusercontent.com/assets/2095041/15532953/e8120ee4-2294-11e6-8ff0-cc6e8f26f995.png)

**Comment by DYS1230** [comment]
我的锅。。。。。

**Comment by VOID001** [comment]
@DYS
Is this a bug caused by your recent patch?

**Comment by VOID001** [comment]
Fixed
